name: GitHub Actions Demo
on: 
  push:
    branches:
    - main
    paths-ignore: 
      - .github/*
  pull_request:
    branches:
    - main
  schedule:
    - cron: "15 6 * * SUN"
  workflow_dispatch:
    
jobs:
  Build:
    name: Builf job
    runs-on: ubuntu-latest
    steps:
      - name: echo event name
        run: 
          echo ${{github.event_name}}
      - name: echo branch name
        run: 
          echo ${{github.ref_name}}
      - name: ls
        run: 
          ls
